eth-url: <enter-your-eth-url>
accounts:
  - address: <enter-your-eth-address1-to-watch>
    alias: <enter-your-eth-address1-alias>
  - address: <enter-your-eth-address2-to-watch>
    alias: <enter-your-eth-address2-alias>
telegram:
  token: <enter-your-tg-token-here>
  username: <enter-your-tg-username-here>
