eth-url: <enter-your-eth-url-here>
addresses:
  - <enter-your-eth-addresses-to-watch-here>
tokens:
  - <enter-your-erc20-tokens-here>
telegram:
  token: <enter-your-tg-token-here>
  username: <enter-your-tg-username-here>
