// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ethereum/go-ethereum/ethclient"
	"github.com/andrei-toptal/eth-listener/token"
)

// Injectors from wire.go:

func WireApp(configPath string) (*App, error) {
	config, err := LoadConfig(configPath)
	if err != nil {
		return nil, err
	}
	tokensDB := newTokensDB()
	accounts := NewAccounts(config)
	mainTelegram := NewTelegram(config)
	client, err := newEthClient(config)
	if err != nil {
		return nil, err
	}
	tokensManager := token.NewTokensManager(client, tokensDB)
	app := NewApp(config, tokensDB, accounts, mainTelegram, client, tokensManager)
	return app, nil
}

// wire.go:

func newEthClient(config *Config) (*ethclient.Client, error) {
	return ethclient.Dial(config.EthUrl)
}

func newTokensDB() token.TokensDB {
	return token.NewTokensDB(TokensDBPath)
}
